// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pahsipyrluqaiuqwzomj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhaHNpcHlybHVxYWl1cXd6b21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDg0NzcsImV4cCI6MjA3NDA4NDQ3N30.PS2q2zuC8vRzA8hJqOG4M28fCFhjY6HRc22VX1mBMyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});